### ISSUE TITLE
Lesson Completion Issue

### ISSUE THREAD

**Issue by CodeAlyx** [learn-co-curriculum/bootstrap-codealong#10]
I can't complete this lesson because it doesn't properly for the lab or recognize that the lab has been forked. It recognizes the submit, however.

**Comment by aturkewi** [comment]
Hey @CodeAlyx I just changed this lab to a readme, so all should need to do now is just click the I'm Done button rather than Fork and Pull Request. 

For future reference, the best way to fix this issue if it comes up again is to re-fork the lab. To do this, you would have to go to your for of the lab on Github, click the settings option for the lab, and delete the repo. Then, go back to the copy of the lab in the `learn-co-students` organization and re-fork it by pressing the Fork button. This should re-send the signal to Learn that you've forked the lab :)

If that still doesn't work, the best thing to do is to use the Report a Bug option in Learn.
